---
title       : Estadística computacional 
subtitle    : Contenido programatico
author      : Kevin Pérez C, Profesor Auxiliar
job         : Departamento de Matemáticas y Estadística - Universidad de Córdoba
logo        : unicordoba3.png
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
widescreen  : true
smaller     : true
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [mathjax, bootstrap, quiz, shiny, interactive]            
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Contenido Programatico

### **Cápitulo I - Introducción a R**

> - Generalidades de [R](https://www.r-project.org/)
    + Historia, Filosofía, [`CRAN`](https://cran.r-project.org/) , Ayuda de R. 
> - Entorno de desarrollo integrado (IDE) [RStudio](https://www.rstudio.com/)
> - Aritmética con R 
> - Números, Operadores Lógicos y Funciones básicas de R.
> - Asignación de variables, expresiones e impresiones de datos.    
> - Tipos de datos en R 
> - Valores faltantes `NA's`
> - Fechas y Expresiones regulares. 

--- 

## Contenido Programatico 

### **Cápitulo II - Objetos en R**

> - Conceptos básicos de objetos
    + Clases, Atributos, Coerción
> - Operadores de Indexación (`[`, `[[`, `$`)
> - Vectores  
> - Matrices 
> - Factores 
> - Marcos de datos (Data Frame)
> - Listas 
> - Objetos definidos por el usuario


--- 

## Contenido Programatico 

### **Cápitulo III - Obtención y Manipulación de datos en R**

> - Lectura archivos locales (Archivos Planos, csv, txt), Excel, etc.  
> - Descarga de archivos y lectura de archivos Web
> - Otras fuentes de datos
    + Bases de datos, archivos comprimidos, Otros _SW Estadístico_. 
> - Manejo de directorios     

--- 

## Contenido Programatico 

### **Cápitulo III - Obtención y Manipulación de datos en R**

> - Datos fuente y su procesamiento
> - Componentes de la limpieza y organización de datos 
> - Seleccionar, filtar, ordenar, adicionar, agrupar y resumir datos 
> - Ceración de nuevas variables 
> - Operaciones sobre conjuntos de datos 

---

## Contenido Programatico 

### **Cápitulo IV - Programación en R**

> - Principios básicos de programación 
> - Estructuras de control 
> - programación de funciones 
> - _Scoping_ y programación funcional
> - funciones vectorizadas 
> - estándar del código y buenas practicas de programación 

---

## Contenido Programatico 

### **Cápitulo V - Sistemas de visualización en R**

> - Principios del análisis gráfico
> - Sistemas de visualización
    + Sistemas `Base`,`Lattice`, `ggplot2` 
> - Sistemas avazandos de visualización `ggvis`, `googleVis`, `ggmaps`
> - Aplicaciones Web con R - Paquetes `shiny`, `shinydashboard`, `htmlwidgest`

--- 

## Contenido Programatico 

### **Cápitulo VI - Modelación Estadística en R**

> - Manejo de variables en R
> - Histogramas y Distribuciones 
> - Escalas de medidas 
> - Medidas de tendencia central y variabilidad 
> - Cálculo de probabiidades en R
> - Intervalos de confianza y pruebas de hipótesis, `t.test`
> - Introducción a la Correlación, Regresión y Análsis de varianza

--- 

## Contenido Programatico 

### **Cápitulo VII - Redacción y publicación de Informes en R**

> - Introducción al `Literate Statistics` 
> - Introducción al marco de trabajo `MarkDown`  
> - Creación y edición de informes en `R MarkDown`
    + Creación y edición de informes, embebido de código `R` y Compilado de archivos `.Rmd`
> - Introducción a $\LaTeX$
> - Introducción al control de versiones `GitHub`
> - Publicación de informes en `R MarkDown` - `GitHub`, `Rpubs`, `shinyapps.io`

---


## Contenido Programatico 

### **Referencias**

> - Advanced R, Hadley Wickham, Chapman & Hall’s R Series, New York, 2013.
> - Data Analysis and Graphics Using R. John Maindonald, John Braun, R. Gill, Cambridge University Press, 2003.   
> - ggplot2: Elegant Graphics for Data Analysis. Hadley Wickham, Springer-Verlag New York, 2016.
> - Mastering Software Development in R , Roger d. Peng et all, LeanPub. 2016. 
> - R Programming for Data Science, Roger d. Peng. LeanPub. 2015. 
> - R for Data Science: Import, Tidy, Transform, Visualize, and Model Data, Hadley Wickham et all, O’REiLLY, New York, 2016.
> - The Art of R Programming: A Tour of Statistical Software Design, Norman Matloff, New York, 2013. 




